#!/usr/bin/env python3
"""Auto-generate missing .doc.md companions for code files.

Walks a directory, finds every code file that has a `Docs:` header
in the first 5 lines, and creates a draft .doc.md skeleton next to
each source file whose referenced companion does not exist.

Idempotent: skips files that already have a companion. Designed to
be called once per skill.

Usage:
    python3 auto_fill_doc_md.py <skill-dir>
"""
from pathlib import Path
import re
import sys

HEAD_LINES = 5
CODE_SUFFIXES = {
    ".py", ".pyi", ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs",
    ".rs", ".go", ".java", ".kt", ".kts", ".scala",
    ".c", ".h", ".cc", ".cpp", ".hpp", ".cs", ".rb", ".php",
    ".swift", ".sh", ".bash", ".zsh", ".yaml", ".yml", ".toml",
}
CODE_FILENAMES = {"Makefile", "Dockerfile", "Justfile"}
EXCLUDE = {
    ".git", "__pycache__", "node_modules", "venv", ".venv",
    "dist", "build", ".mypy_cache", ".pytest_cache", ".ruff_cache",
    "site-packages", ".egg-info",
}
DOCS_RE = re.compile(
    r"^\s*(?:#|//|/\*|\*|--|;)?\s*Docs:\s*(?P<doc>[^\s*]+?\.doc\.md)"
)

SKELETON_TEMPLATE = """# {filename}

> **Status: DRAFT** — auto-generated by `auto-fill-doc-md.sh`. Every
> `<TODO: …>` block needs a human to fill it in.

**Purpose:** <TODO: one-line summary of what this file does>

**Source file:** `{rel_path}` ({language})

**Header excerpt:**

```
{header}
```

---

## What it does

<TODO: 1-paragraph elevator pitch. What is this file responsible for?
What would break if it were deleted?>

## Dependencies

<TODO: list the key imports / dependencies and WHY each is used>

## Important config

<TODO: magic numbers, env vars, config keys with units / constraints>

## Why these decisions

<TODO: non-obvious choices (why NOT the obvious approach)>

## Usage example

```bash
<TODO: 1-3 line usage example>
```

## Known caveats

<TODO: footguns, edge cases, security notes>
"""


def main() -> int:
    if len(sys.argv) != 2:
        print("Usage: auto_fill_doc_md.py <skill-dir>", file=sys.stderr)
        return 1

    root = Path(sys.argv[1]).resolve()
    if not root.is_dir():
        print(f"Not a directory: {root}", file=sys.stderr)
        return 1

    created = 0
    skipped = 0
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        if any(part in EXCLUDE for part in path.parts):
            continue
        if path.name not in CODE_FILENAMES and path.suffix not in CODE_SUFFIXES:
            continue

        # Extract Docs: reference from first HEAD_LINES lines
        try:
            with path.open("r", encoding="utf-8", errors="ignore") as fh:
                doc = None
                for _ in range(HEAD_LINES):
                    line = fh.readline()
                    if line == "":
                        break
                    m = DOCS_RE.match(line)
                    if m:
                        doc = m.group("doc")
                        break
        except OSError:
            continue
        if doc is None:
            continue

        # Skip if Docs: line is not in the first 5 lines (handled above)
        # Resolve companion path: relative to source file's directory
        companion = (path.parent / doc).resolve()
        if companion.is_file():
            skipped += 1
            continue

        # Determine language label
        if path.suffix in (".py", ".pyi"):
            language = "Python"
        elif path.suffix:
            language = path.suffix.lstrip(".").upper()
        else:
            language = "Shell" if path.name in CODE_FILENAMES else "Config"

        # Read header excerpt (first 8 lines)
        try:
            with path.open("r", encoding="utf-8", errors="ignore") as fh:
                header = "".join(fh.readline() for _ in range(8))
        except OSError:
            header = ""

        rel_path = path.relative_to(root)
        skeleton = SKELETON_TEMPLATE.format(
            filename=path.name,
            rel_path=rel_path,
            language=language,
            header=header,
        )
        companion.parent.mkdir(parents=True, exist_ok=True)
        companion.write_text(skeleton, encoding="utf-8")
        print(f"  [create] {companion.relative_to(root)}")
        created += 1

    print(f"\nDone. Created {created}, skipped {skipped} (already exist).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
